### ISSUE TITLE
SCSSファイルのcolorを変数にする

### ISSUE THREAD

**Issue by yuki0920** [yuki0920/supplebox#235]
example)
```scss
$light-gray: #777;
.
.
.
h2 {
  .
  .
  .
  color: $light-gray;
}
```
